In [1]:
import sys
sys.version

'3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]'

In [2]:
# 6.5.2 Create Heatmaps for Weather Parameters

In [3]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [4]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Tiksi,RU,2022-03-14 02:30:27,71.6872,128.8694,-15.34,98,98,1.52
1,1,Bethel,US,2022-03-14 02:30:28,41.3712,-73.4140,28.65,72,20,5.75
2,2,San Patricio,US,2022-03-14 02:30:28,28.0170,-97.5169,64.26,77,84,8.52
3,3,Klaksvik,FO,2022-03-14 02:30:28,62.2266,-6.5890,45.52,94,65,14.56
4,4,Nanortalik,GL,2022-03-14 02:30:29,60.1432,-45.2371,29.41,92,100,19.73

In [5]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [6]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [7]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

InvalidWeightException: -15.34 is not a valid weight. Weights must be non-negative.

In [8]:
# Get the maximum temperature.
#max_temp = city_data_df["Max Temp"]
#temps = []
#for temp in max_temp:
#    temps.append(max(temp, 0))
    
# In the for loop, we're using the max() function to get the largest value between the temp and 0. 
# If the temp is less than 0, then 0 will be added to the list in its place. 
# Otherwise, the temp is added to the list.   

#Above code is replaced with the list comprehension below

In [9]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Create the Percent Humidity Heatmap

In [11]:
# Heatmap of percent Humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Create the Percent Cloudiness Heatmap

In [13]:
# Heatmap of percent Cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of percent Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [26]:
# 6.5.3 Get Vacation Criteria

In [27]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [28]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
5,5,Hilo,US,2022-03-14 02:27:21,19.7297,-155.0900,78.53,72,100,12.66
6,6,Hithadhoo,MV,2022-03-14 02:30:29,-0.6000,73.0833,82.89,71,100,4.43
7,7,Mount Gambier,AU,2022-03-14 02:30:29,-37.8333,140.7667,76.91,61,100,9.22
10,10,Belmonte,BR,2022-03-14 02:30:30,-15.8631,-38.8828,77.86,86,92,5.08
14,14,Vaini,TO,2022-03-14 02:30:32,-21.2000,-175.2000,84.36,79,40,5.75
23,23,Rikitea,PF,2022-03-14 02:30:34,-23.1203,-134.9692,80.33,71,88,14.38
25,25,Port Pirie,AU,2022-03-14 02:30:35,-33.1833,138.0167,89.69,24,70,6.87
26,26,Yara,CU,2022-03-14 02:30:35,20.2753,-76.9533,75.25,79,29,9.35
29,29,Sinnamary,GF,2022-03-14 02:30:36,5.3833,-52.9500,76.23,93,100,11.16
30,30,Aquiraz,BR,2022-03-14 02:30:01,-3.9014,-38.3911,82.06,82,95,4.14

In [29]:
#check for null values - all work
#preferred_cities_df.count()
preferred_cities_df.isnull().sum()
#preferred_cities_df.notnull().sum()

# If you have some rows with null values, 
# you'll need to drop them using the dropna() method at the end of your filtering statement 
# when you are creating the new DataFrame.

City_ID       0
City          0
Country       0
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [30]:
preferred_cities_df.count()

City_ID       149
City          149
Country       149
Date          149
Lat           149
Lng           149
Max Temp      149
Humidity      149
Cloudiness    149
Wind Speed    149
dtype: int64

In [20]:
# 6.5.4 Map Vacation Criteria

In [31]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

             City Country  Max Temp      Lat       Lng Hotel Name
5            Hilo      US     78.53  19.7297 -155.0900
6       Hithadhoo      MV     82.89  -0.6000   73.0833
7   Mount Gambier      AU     76.91 -37.8333  140.7667
10       Belmonte      BR     77.86 -15.8631  -38.8828
14          Vaini      TO     84.36 -21.2000 -175.2000
23        Rikitea      PF     80.33 -23.1203 -134.9692
25     Port Pirie      AU     89.69 -33.1833  138.0167
26           Yara      CU     75.25  20.2753  -76.9533
29      Sinnamary      GF     76.23   5.3833  -52.9500
30        Aquiraz      BR     82.06  -3.9014  -38.3911

In [32]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [33]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [34]:
hotel_df.head(25)

,City,Country,Max Temp,Lat,Lng,Hotel Name
5,Hilo,US,78.53,19.7297,-155.0900,Hilo Hawaiian Hotel
6,Hithadhoo,MV,82.89,-0.6000,73.0833,Scoop Guest House
7,Mount Gambier,AU,76.91,-37.8333,140.7667,The Commodore
10,Belmonte,BR,77.86,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
14,Vaini,TO,84.36,-21.2000,-175.2000,Keleti Beach Resort
23,Rikitea,PF,80.33,-23.1203,-134.9692,People ThankYou
25,Port Pirie,AU,89.69,-33.1833,138.0167,John Pirie Motor Inn
26,Yara,CU,75.25,20.2753,-76.9533,Casa de Margarita Puebla Lorente
29,Sinnamary,GF,76.23,5.3833,-52.9500,ALETHEIA Appartement Sinnamary
30,Aquiraz,BR,82.06,-3.9014,-38.3911,Pousada Rua Camurupim
35,Butaritari,KI,81.66,3.0707,172.7902,Isles Sunset Lodge
41,Balabac,PH,84.74,7.9868,117.0645,Batalla’s Lodging House
42,Kapaa,US,79.12,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
44,Byron Bay,AU,76.89,-28.6500,153.6167,Backpackers Inn
45,Atuona,PF,79.12,-9.8000,-139.0333,Villa Enata
47,Kavaratti,IN,83.19,10.5669,72.6420,Hotels in Lakshadweep Islands
49,Mahebourg,MU,79.25,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
50,Geraldton,AU,81.01,-28.7667,114.6000,Broadwater Mariner Resort
51,Carnarvon,AU,82.47,-24.8667,113.6333,Hospitality Carnarvon
57,Avarua,CK,84.25,-21.2078,-159.7750,Paradise Inn
59,Trat,TH,87.82,12.5000,102.5000,สวนหนิง-อัศ
61,Isangel,VU,85.01,-19.5500,169.2667,Tanna Lodge
63,Faanui,PF,82.09,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
64,Bengkulu,ID,81.03,-3.8004,102.2655,Grage Hotel Bengkulu
67,Victoria,HK,79.95,22.2855,114.1577,Mini Hotel Central

In [35]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [36]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [37]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [38]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [39]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))